### ISSUE TITLE
Not displaying equations on  both ios and Android emulator

### ISSUE THREAD

**Issue by vinukn335** [shahzadakram67/flutter_tex#3]
`Launching lib/main.dart on Android SDK built for x86 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter ( 5185): Server running on http://localhost:8080
D/        ( 5185): HostConnection::get() New Host Connection established 0xd10ff280, tid 5400
D/        ( 5185): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_dma_v1 GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation( 5185): eglMakeCurrent: 0xecf102a0: ver 3 0 (tinfo 0xe1151f70)
Flutter is taking longer than expected to report its views. Still trying...
D/        ( 5185): HostConnection::get() New Host Connection established 0xe5b159c0, tid 5511
D/        ( 5185): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_dma_v1 GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation( 5185): eglMakeCurrent: 0xecf11140: ver 3 0 (tinfo 0xe5b00570)
I/Choreographer( 5185): Skipped 1210 frames!  The application may be doing too much work on its main thread.
I/le.mathjax_dem( 5185): NativeAlloc concurrent copying GC freed 2518(228KB) AllocSpace objects, 3(60KB) LOS objects, 57% free, 1146KB/2682KB, paused 823us total 353.286ms
D/EGL_emulation( 5185): eglCreateContext: 0xecf11800: maj 3 min 0 rcv 3
D/EGL_emulation( 5185): eglMakeCurrent: 0xecf11800: ver 3 0 (tinfo 0xecfda6b0)
I/Choreographer( 5185): Skipped 50 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 5185): eglMakeCurrent: 0xecf10000: ver 3 0 (tinfo 0xd11c12c0)
I/OpenGLRenderer( 5185): Davey! duration=911ms; Flags=1, IntendedVsync=352978199753, Vsync=353811533053, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=353813616000, AnimationStart=353813686000, PerformTraversalsStart=353813753000, DrawStart=353831606000, SyncQueued=353832993000, SyncStart=353834079000, IssueDrawCommandsStart=353834299000, SwapBuffers=353868569000, FrameCompleted=353891249000, DequeueBufferDuration=8728000, QueueBufferDuration=272000, 
I/flutter ( 5185): Server running on http://localhost:8080
W/Gralloc3( 5185): allocator 3.x is not supported
D/        ( 5185): HostConnection::get() New Host Connection established 0xe11b9dc0, tid 5202
D/        ( 5185): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_dma_v1 GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/        ( 5185): HostConnection::get() New Host Connection established 0xe5b152c0, tid 5203
D/        ( 5185): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_dma_v1 GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
I/WebViewFactory( 5185): Loading com.google.android.webview version 73.0.3683.20 (code 368302018)
I/le.mathjax_dem( 5185): The ClassLoaderContext is a special shared library.
I/le.mathjax_dem( 5185): The ClassLoaderContext is a special shared library.
I/cr_LibraryLoader( 5185): Time to load native libraries: 2 ms (timestamps 8155-8157)
I/chromium( 5185): [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader( 5185): Expected native library version number "73.0.3683.20", actual native library version number "73.0.3683.20"
W/cr_ChildProcLH( 5185): Create a new ChildConnectionAllocator with package name = com.google.android.webview, sandboxed = true
I/cr_BrowserStartup( 5185): Initializing chromium process, singleProcess=false
W/le.mathjax_dem( 5185): Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (greylist, reflection)
E/chromium( 5185): [ERROR:filesystem_posix.cc(89)] stat /data/user/0/com.example.mathjax_demo/cache/WebView/Crashpad: No such file or directory (2)
E/chromium( 5185): [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/com.example.mathjax_demo/cache/WebView/Crashpad: No such file or directory (2)
D/        ( 5185): HostConnection::get() New Host Connection established 0xce0773c0, tid 5510
D/        ( 5185): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_dma_v1 GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation( 5185): eglMakeCurrent: 0xecf11800: ver 3 0 (tinfo 0xd11c1890)
W/le.mathjax_dem( 5185): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (greylist, reflection)
W/le.mathjax_dem( 5185): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (greylist, reflection)
W/le.mathjax_dem( 5185): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection)
W/le.mathjax_dem( 5185): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection)
W/le.mathjax_dem( 5185): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection)
W/le.mathjax_dem( 5185): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection)
W/le.mathjax_dem( 5185): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection)
W/le.mathjax_dem( 5185): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (greylist, reflection)
W/cr_media( 5185): Requires BLUETOOTH permission
D/EGL_emulation( 5185): eglCreateContext: 0xc852db00: maj 3 min 0 rcv 3
D/EGL_emulation( 5185): eglMakeCurrent: 0xc852db00: ver 3 0 (tinfo 0xecfda6b0)
D/        ( 5185): HostConnection::get() New Host Connection established 0xe5b19480, tid 5586
D/        ( 5185): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_dma_v1 GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation( 5185): eglMakeCurrent: 0xecf10000: ver 3 0 (tinfo 0xd11c12c0)
E/eglCodecCommon( 5185): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon( 5185): glUtilsParamSize: unknow param 0x000088ef
D/EGL_emulation( 5185): eglMakeCurrent: 0xecf10000: ver 3 0 (tinfo 0xd11c12c0)
D/EGL_emulation( 5185): eglMakeCurrent: 0xecf10000: ver 3 0 (tinfo 0xd11c12c0)
D/EGL_emulation( 5185): eglMakeCurrent: 0xecf10000: ver 3 0 (tinfo 0xd11c12c0)
D/NetworkSecurityConfig( 5185): No Network Security Config specified, using platform default
I/VideoCapabilities( 5185): Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil( 5185): HW encoder for video/avc is not available on this device.
D/EGL_emulation( 5185): eglMakeCurrent: 0xecf10000: ver 3 0 (tinfo 0xd11c12c0)
D/EGL_emulation( 5185): eglCreateContext: 0xe5b01240: maj 3 min 0 rcv 3
D/EGL_emulation( 5185): eglMakeCurrent: 0xe5b01240: ver 3 0 (tinfo 0xe5b00a70)
E/eglCodecCommon( 5185): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon( 5185): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon( 5185): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon( 5185): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon( 5185): glUtilsParamSize: unknow param 0x000088ef
E/eglCodecCommon( 5185): glUtilsParamSize: unknow param 0x000088ef

`
![Screenshot_1552829756](https://user-images.githubusercontent.com/47185599/54491861-bc946d80-48e7-11e9-8bd0-d2a5281a473c.png)

in ios
`Launching lib/main.dart on iPhone X in debug mode...
Xcode build done.                                            9.5s
flutter: Server running on http://localhost:8080
[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding

`
![Simulator Screen Shot - iPhone X - 2019-03-17 at 19 08 35](https://user-images.githubusercontent.com/47185599/54491908-16953300-48e8-11e9-8523-b56c91ee71ee.png)

**Comment by shahzadakram67** [comment]
On android Please try with API > 23

**Comment by shahzadakram67** [comment]
Make sure to add this line in your AndroidManifest.xml under `application` like this.

```xml
<application
       
       android:usesCleartextTraffic="true">
       
</application>
```

**Comment by vinukn335** [comment]
What about Ios Error?

**Comment by shahzadakram67** [comment]
Bro Sorry I don't own a mac and can't say anything now I have mentioned this is in README.

**Comment by felipeaugustox** [comment]
I get this error in a intermittent way, when that happened I just refresh the simulator and it worked, not sure about what could it be, @shahzadakram67 do you know if the server can recover itself if it breaks? or if it's possible to break in some way? I think that should be a good thing to think about.

**Comment by shahzadakram67** [comment]
@felipeaugustox bro please try `flutter clean` uninstall your existing app and then try this.
I think this issue would be for the first time when we start an old app and when we reload it, it wouldn't show anymore unless for the next time..

**Comment by vinukn335** [comment]
Fixed ios bug
![Simulator Screen Shot - iPhone X - 2019-03-21 at 20 45 51](https://user-images.githubusercontent.com/47185599/54762794-c6391080-4c1a-11e9-8138-99993ddc5241.png)

Added dependency 
`dependencies:
  webview_flutter: ^0.3.5
`

Added following codes in  project_file/ios/Runner/Info.plist
`<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
`

**Comment by shahzadakram67** [comment]
@vinukn335 bro can you try this without adding ` dependencies: webview_flutter: ^0.3.5 ` as package already has dependency added. Please let me know if it works.

**Comment by OscarEReyes** [comment]
I am having issues loading running this package on an emulator as well. 
It works on my physical android device, but shows nothing on the emulator.

I made sure to include the clear text line on the manifest file.

Should I open a separate issue?
